-- ====================================================================
-- SCRIPTS DE LA BASE DE DATOS ORACLE - CLOUD NATIVE II
-- EVALUACIÓN FINAL TRANSVERSAL - GRUPO 7
-- ====================================================================

-- 1. Eliminar tablas si existen (para evitar errores en ejecuciones limpias)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INSCRIPCION_CURSO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CURSO CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE INSCRIPCION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RESUMEN_COMPRA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 2. Creación de la tabla CURSO
CREATE TABLE CURSO (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(255) NOT NULL,
    instructor VARCHAR2(255) NOT NULL,
    duracion VARCHAR2(100),
    costo NUMBER(19, 2) NOT NULL,
    CONSTRAINT pk_curso PRIMARY KEY (id)
);

-- 3. Creación de la tabla INSCRIPCION
CREATE TABLE INSCRIPCION (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre_estudiante VARCHAR2(255) NOT NULL,
    total_a_pagar NUMBER(19, 2) NOT NULL,
    CONSTRAINT pk_inscripcion PRIMARY KEY (id)
);

-- 4. Creación de la tabla intermedia INSCRIPCION_CURSO (Relación Many-to-Many)
CREATE TABLE INSCRIPCION_CURSO (
    inscripcion_id NUMBER NOT NULL,
    curso_id NUMBER NOT NULL,
    CONSTRAINT pk_inscripcion_curso PRIMARY KEY (inscripcion_id, curso_id),
    CONSTRAINT fk_insc_curso_inscripcion FOREIGN KEY (inscripcion_id) REFERENCES INSCRIPCION(id) ON DELETE CASCADE,
    CONSTRAINT fk_insc_curso_curso FOREIGN KEY (curso_id) REFERENCES CURSO(id) ON DELETE CASCADE
);

-- 5. Creación de la tabla RESUMEN_COMPRA (Consumidor de RabbitMQ)
CREATE TABLE RESUMEN_COMPRA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    inscripcion_id NUMBER NOT NULL,
    resumen VARCHAR2(2000) NOT NULL,
    CONSTRAINT pk_resumen_compra PRIMARY KEY (id)
);

-- ====================================================================
-- SEED DATA - INSERCIÓN DE CURSOS DE PRUEBA
-- ====================================================================
INSERT INTO CURSO (nombre, instructor, duracion, costo) VALUES ('Desarrollo Cloud Native II', 'Carlos Gomez', '60 horas', 120000);
INSERT INTO CURSO (nombre, instructor, duracion, costo) VALUES ('Arquitectura de Microservicios', 'Ana Maria Silva', '45 horas', 150000);
INSERT INTO CURSO (nombre, instructor, duracion, costo) VALUES ('Seguridad Aplicada y OIDC', 'Roberto Prado', '30 horas', 95000);
INSERT INTO CURSO (nombre, instructor, duracion, costo) VALUES ('DevOps y Pipelines de Despliegue', 'Laura Martinez', '50 horas', 135000);
INSERT INTO CURSO (nombre, instructor, duracion, costo) VALUES ('Bases de Datos Cloud con Oracle', 'Esteban Munoz', '40 horas', 110000);

COMMIT;

-- ====================================================================
-- 6. SIMULAR MENSAJES DE RABBITMQ GUARDADOS
-- ====================================================================
INSERT INTO resumen_compra (inscripcion_id, resumen) VALUES (1, '=== RESUMEN === ID: 1, Estudiante: Leonardo Bustamante, Cursos: AWS Cloud, Spring Boot. Total: $250000');
INSERT INTO resumen_compra (inscripcion_id, resumen) VALUES (2, '=== RESUMEN === ID: 2, Estudiante: Ana Torres, Cursos: EFT Cloud Native II. Total: $50000');

-- 7. GUARDAR CAMBIOS
COMMIT;

-- ====================================================================
-- 8. CONSULTAS DE VERIFICACIÓN Y LIMPIEZA
-- ====================================================================

-- Verificar todos los cursos disponibles en el sistema
SELECT * FROM curso;

-- Contar cuántos mensajes de resumen de compra (RabbitMQ) se han procesado en total
SELECT COUNT(*) AS total_mensajes_procesados
FROM resumen_compra;

-- Ver el detalle de los mensajes procesados y guardados
SELECT * FROM resumen_compra;

-- Ver el detalle de las inscripciones registradas
SELECT * FROM inscripcion;

-- ====================================================================
-- 9. LIMPIEZA DE DATOS (Solo usar para reiniciar las pruebas)
-- ====================================================================
-- Eliminar los registros de prueba generados
DELETE FROM resumen_compra WHERE inscripcion_id IN (1, 2);
DELETE FROM inscripcion_curso WHERE inscripcion_id IN (1, 2);
DELETE FROM inscripcion WHERE id IN (1, 2);

-- Guardar los cambios de la limpieza
COMMIT;
