# Configuración de Oracle Cloud
spring.datasource.url=jdbc:oracle:thin:@${ORACLE_TNS_NAME}
spring.datasource.username=${ORACLE_DB_USER}
spring.datasource.password=${ORACLE_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=${TNS_ADMIN_PATH:/app/wallet}
spring.datasource.hikari.data-source-properties.oracle.net.wallet_location=(SOURCE=(METHOD=file)(METHOD_DATA=(DIRECTORY=${TNS_ADMIN_PATH:/app/wallet})))
# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Configuración de Spring Security OAuth2 (Microsoft Entra ID)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://duocazurecloudn.b2clogin.com/76b75f28-e0f9-4305-9b31-f6f69d880cfe/v2.0/
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://duocazurecloudn.b2clogin.com/76b75f28-e0f9-4305-9b31-f6f69d880cfe/B2C_1_DuocDemoAzure_registro_login/discovery/v2.0/keys

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG